// Full ISO-3166 list with nationality (demonym) labels + flag emojis.
// `value` is what gets stored, `label` is what's shown in the picker.
export type Nationality = { code: string; flag: string; label: string };

export const NATIONALITIES: Nationality[] = [
  { code: "AF", flag: "🇦🇫", label: "Afghan" },
  { code: "AL", flag: "🇦🇱", label: "Albanian" },
  { code: "DZ", flag: "🇩🇿", label: "Algerian" },
  { code: "AD", flag: "🇦🇩", label: "Andorran" },
  { code: "AO", flag: "🇦🇴", label: "Angolan" },
  { code: "AG", flag: "🇦🇬", label: "Antiguan or Barbudan" },
  { code: "AR", flag: "🇦🇷", label: "Argentine" },
  { code: "AM", flag: "🇦🇲", label: "Armenian" },
  { code: "AU", flag: "🇦🇺", label: "Australian" },
  { code: "AT", flag: "🇦🇹", label: "Austrian" },
  { code: "AZ", flag: "🇦🇿", label: "Azerbaijani" },
  { code: "BS", flag: "🇧🇸", label: "Bahamian" },
  { code: "BH", flag: "🇧🇭", label: "Bahraini" },
  { code: "BD", flag: "🇧🇩", label: "Bangladeshi" },
  { code: "BB", flag: "🇧🇧", label: "Barbadian" },
  { code: "BY", flag: "🇧🇾", label: "Belarusian" },
  { code: "BE", flag: "🇧🇪", label: "Belgian" },
  { code: "BZ", flag: "🇧🇿", label: "Belizean" },
  { code: "BJ", flag: "🇧🇯", label: "Beninese" },
  { code: "BT", flag: "🇧🇹", label: "Bhutanese" },
  { code: "BO", flag: "🇧🇴", label: "Bolivian" },
  { code: "BA", flag: "🇧🇦", label: "Bosnian or Herzegovinian" },
  { code: "BW", flag: "🇧🇼", label: "Botswanan" },
  { code: "BR", flag: "🇧🇷", label: "Brazilian" },
  { code: "BN", flag: "🇧🇳", label: "Bruneian" },
  { code: "BG", flag: "🇧🇬", label: "Bulgarian" },
  { code: "BF", flag: "🇧🇫", label: "Burkinabé" },
  { code: "BI", flag: "🇧🇮", label: "Burundian" },
  { code: "KH", flag: "🇰🇭", label: "Cambodian" },
  { code: "CM", flag: "🇨🇲", label: "Cameroonian" },
  { code: "CA", flag: "🇨🇦", label: "Canadian" },
  { code: "CV", flag: "🇨🇻", label: "Cape Verdean" },
  { code: "CF", flag: "🇨🇫", label: "Central African" },
  { code: "TD", flag: "🇹🇩", label: "Chadian" },
  { code: "CL", flag: "🇨🇱", label: "Chilean" },
  { code: "CN", flag: "🇨🇳", label: "Chinese" },
  { code: "CO", flag: "🇨🇴", label: "Colombian" },
  { code: "KM", flag: "🇰🇲", label: "Comoran" },
  { code: "CG", flag: "🇨🇬", label: "Congolese (Republic)" },
  { code: "CD", flag: "🇨🇩", label: "Congolese (DRC)" },
  { code: "CR", flag: "🇨🇷", label: "Costa Rican" },
  { code: "CI", flag: "🇨🇮", label: "Ivorian" },
  { code: "HR", flag: "🇭🇷", label: "Croatian" },
  { code: "CU", flag: "🇨🇺", label: "Cuban" },
  { code: "CY", flag: "🇨🇾", label: "Cypriot" },
  { code: "CZ", flag: "🇨🇿", label: "Czech" },
  { code: "DK", flag: "🇩🇰", label: "Danish" },
  { code: "DJ", flag: "🇩🇯", label: "Djiboutian" },
  { code: "DM", flag: "🇩🇲", label: "Dominican (Dominica)" },
  { code: "DO", flag: "🇩🇴", label: "Dominican (DR)" },
  { code: "EC", flag: "🇪🇨", label: "Ecuadorian" },
  { code: "EG", flag: "🇪🇬", label: "Egyptian" },
  { code: "SV", flag: "🇸🇻", label: "Salvadoran" },
  { code: "GQ", flag: "🇬🇶", label: "Equatorial Guinean" },
  { code: "ER", flag: "🇪🇷", label: "Eritrean" },
  { code: "EE", flag: "🇪🇪", label: "Estonian" },
  { code: "SZ", flag: "🇸🇿", label: "Swazi" },
  { code: "ET", flag: "🇪🇹", label: "Ethiopian" },
  { code: "FJ", flag: "🇫🇯", label: "Fijian" },
  { code: "FI", flag: "🇫🇮", label: "Finnish" },
  { code: "FR", flag: "🇫🇷", label: "French" },
  { code: "GA", flag: "🇬🇦", label: "Gabonese" },
  { code: "GM", flag: "🇬🇲", label: "Gambian" },
  { code: "GE", flag: "🇬🇪", label: "Georgian" },
  { code: "DE", flag: "🇩🇪", label: "German" },
  { code: "GH", flag: "🇬🇭", label: "Ghanaian" },
  { code: "GR", flag: "🇬🇷", label: "Greek" },
  { code: "GD", flag: "🇬🇩", label: "Grenadian" },
  { code: "GT", flag: "🇬🇹", label: "Guatemalan" },
  { code: "GN", flag: "🇬🇳", label: "Guinean" },
  { code: "GW", flag: "🇬🇼", label: "Bissau-Guinean" },
  { code: "GY", flag: "🇬🇾", label: "Guyanese" },
  { code: "HT", flag: "🇭🇹", label: "Haitian" },
  { code: "HN", flag: "🇭🇳", label: "Honduran" },
  { code: "HU", flag: "🇭🇺", label: "Hungarian" },
  { code: "IS", flag: "🇮🇸", label: "Icelandic" },
  { code: "IN", flag: "🇮🇳", label: "Indian" },
  { code: "ID", flag: "🇮🇩", label: "Indonesian" },
  { code: "IR", flag: "🇮🇷", label: "Iranian" },
  { code: "IQ", flag: "🇮🇶", label: "Iraqi" },
  { code: "IE", flag: "🇮🇪", label: "Irish" },
  { code: "IL", flag: "🇮🇱", label: "Israeli" },
  { code: "IT", flag: "🇮🇹", label: "Italian" },
  { code: "JM", flag: "🇯🇲", label: "Jamaican" },
  { code: "JP", flag: "🇯🇵", label: "Japanese" },
  { code: "JO", flag: "🇯🇴", label: "Jordanian" },
  { code: "KZ", flag: "🇰🇿", label: "Kazakhstani" },
  { code: "KE", flag: "🇰🇪", label: "Kenyan" },
  { code: "KI", flag: "🇰🇮", label: "I-Kiribati" },
  { code: "KP", flag: "🇰🇵", label: "North Korean" },
  { code: "KR", flag: "🇰🇷", label: "South Korean" },
  { code: "KW", flag: "🇰🇼", label: "Kuwaiti" },
  { code: "KG", flag: "🇰🇬", label: "Kyrgyz" },
  { code: "LA", flag: "🇱🇦", label: "Lao" },
  { code: "LV", flag: "🇱🇻", label: "Latvian" },
  { code: "LB", flag: "🇱🇧", label: "Lebanese" },
  { code: "LS", flag: "🇱🇸", label: "Mosotho" },
  { code: "LR", flag: "🇱🇷", label: "Liberian" },
  { code: "LY", flag: "🇱🇾", label: "Libyan" },
  { code: "LI", flag: "🇱🇮", label: "Liechtensteiner" },
  { code: "LT", flag: "🇱🇹", label: "Lithuanian" },
  { code: "LU", flag: "🇱🇺", label: "Luxembourger" },
  { code: "MG", flag: "🇲🇬", label: "Malagasy" },
  { code: "MW", flag: "🇲🇼", label: "Malawian" },
  { code: "MY", flag: "🇲🇾", label: "Malaysian" },
  { code: "MV", flag: "🇲🇻", label: "Maldivian" },
  { code: "ML", flag: "🇲🇱", label: "Malian" },
  { code: "MT", flag: "🇲🇹", label: "Maltese" },
  { code: "MH", flag: "🇲🇭", label: "Marshallese" },
  { code: "MR", flag: "🇲🇷", label: "Mauritanian" },
  { code: "MU", flag: "🇲🇺", label: "Mauritian" },
  { code: "MX", flag: "🇲🇽", label: "Mexican" },
  { code: "FM", flag: "🇫🇲", label: "Micronesian" },
  { code: "MD", flag: "🇲🇩", label: "Moldovan" },
  { code: "MC", flag: "🇲🇨", label: "Monégasque" },
  { code: "MN", flag: "🇲🇳", label: "Mongolian" },
  { code: "ME", flag: "🇲🇪", label: "Montenegrin" },
  { code: "MA", flag: "🇲🇦", label: "Moroccan" },
  { code: "MZ", flag: "🇲🇿", label: "Mozambican" },
  { code: "MM", flag: "🇲🇲", label: "Burmese" },
  { code: "NA", flag: "🇳🇦", label: "Namibian" },
  { code: "NR", flag: "🇳🇷", label: "Nauruan" },
  { code: "NP", flag: "🇳🇵", label: "Nepali" },
  { code: "NL", flag: "🇳🇱", label: "Dutch" },
  { code: "NZ", flag: "🇳🇿", label: "New Zealander" },
  { code: "NI", flag: "🇳🇮", label: "Nicaraguan" },
  { code: "NE", flag: "🇳🇪", label: "Nigerien" },
  { code: "NG", flag: "🇳🇬", label: "Nigerian" },
  { code: "MK", flag: "🇲🇰", label: "Macedonian" },
  { code: "NO", flag: "🇳🇴", label: "Norwegian" },
  { code: "OM", flag: "🇴🇲", label: "Omani" },
  { code: "PK", flag: "🇵🇰", label: "Pakistani" },
  { code: "PW", flag: "🇵🇼", label: "Palauan" },
  { code: "PS", flag: "🇵🇸", label: "Palestinian" },
  { code: "PA", flag: "🇵🇦", label: "Panamanian" },
  { code: "PG", flag: "🇵🇬", label: "Papua New Guinean" },
  { code: "PY", flag: "🇵🇾", label: "Paraguayan" },
  { code: "PE", flag: "🇵🇪", label: "Peruvian" },
  { code: "PH", flag: "🇵🇭", label: "Filipino" },
  { code: "PL", flag: "🇵🇱", label: "Polish" },
  { code: "PT", flag: "🇵🇹", label: "Portuguese" },
  { code: "QA", flag: "🇶🇦", label: "Qatari" },
  { code: "RO", flag: "🇷🇴", label: "Romanian" },
  { code: "RU", flag: "🇷🇺", label: "Russian" },
  { code: "RW", flag: "🇷🇼", label: "Rwandan" },
  { code: "KN", flag: "🇰🇳", label: "Kittitian or Nevisian" },
  { code: "LC", flag: "🇱🇨", label: "Saint Lucian" },
  { code: "VC", flag: "🇻🇨", label: "Saint Vincentian" },
  { code: "WS", flag: "🇼🇸", label: "Samoan" },
  { code: "SM", flag: "🇸🇲", label: "Sammarinese" },
  { code: "ST", flag: "🇸🇹", label: "São Toméan" },
  { code: "SA", flag: "🇸🇦", label: "Saudi" },
  { code: "SN", flag: "🇸🇳", label: "Senegalese" },
  { code: "RS", flag: "🇷🇸", label: "Serbian" },
  { code: "SC", flag: "🇸🇨", label: "Seychellois" },
  { code: "SL", flag: "🇸🇱", label: "Sierra Leonean" },
  { code: "SG", flag: "🇸🇬", label: "Singaporean" },
  { code: "SK", flag: "🇸🇰", label: "Slovak" },
  { code: "SI", flag: "🇸🇮", label: "Slovenian" },
  { code: "SB", flag: "🇸🇧", label: "Solomon Islander" },
  { code: "SO", flag: "🇸🇴", label: "Somali" },
  { code: "ZA", flag: "🇿🇦", label: "South African" },
  { code: "SS", flag: "🇸🇸", label: "South Sudanese" },
  { code: "ES", flag: "🇪🇸", label: "Spanish" },
  { code: "LK", flag: "🇱🇰", label: "Sri Lankan" },
  { code: "SD", flag: "🇸🇩", label: "Sudanese" },
  { code: "SR", flag: "🇸🇷", label: "Surinamese" },
  { code: "SE", flag: "🇸🇪", label: "Swedish" },
  { code: "CH", flag: "🇨🇭", label: "Swiss" },
  { code: "SY", flag: "🇸🇾", label: "Syrian" },
  { code: "TW", flag: "🇹🇼", label: "Taiwanese" },
  { code: "TJ", flag: "🇹🇯", label: "Tajik" },
  { code: "TZ", flag: "🇹🇿", label: "Tanzanian" },
  { code: "TH", flag: "🇹🇭", label: "Thai" },
  { code: "TL", flag: "🇹🇱", label: "Timorese" },
  { code: "TG", flag: "🇹🇬", label: "Togolese" },
  { code: "TO", flag: "🇹🇴", label: "Tongan" },
  { code: "TT", flag: "🇹🇹", label: "Trinidadian or Tobagonian" },
  { code: "TN", flag: "🇹🇳", label: "Tunisian" },
  { code: "TR", flag: "🇹🇷", label: "Turkish" },
  { code: "TM", flag: "🇹🇲", label: "Turkmen" },
  { code: "TV", flag: "🇹🇻", label: "Tuvaluan" },
  { code: "UG", flag: "🇺🇬", label: "Ugandan" },
  { code: "UA", flag: "🇺🇦", label: "Ukrainian" },
  { code: "AE", flag: "🇦🇪", label: "Emirati" },
  { code: "GB", flag: "🇬🇧", label: "British" },
  { code: "US", flag: "🇺🇸", label: "American" },
  { code: "UY", flag: "🇺🇾", label: "Uruguayan" },
  { code: "UZ", flag: "🇺🇿", label: "Uzbek" },
  { code: "VU", flag: "🇻🇺", label: "Ni-Vanuatu" },
  { code: "VA", flag: "🇻🇦", label: "Vatican" },
  { code: "VE", flag: "🇻🇪", label: "Venezuelan" },
  { code: "VN", flag: "🇻🇳", label: "Vietnamese" },
  { code: "YE", flag: "🇾🇪", label: "Yemeni" },
  { code: "ZM", flag: "🇿🇲", label: "Zambian" },
  { code: "ZW", flag: "🇿🇼", label: "Zimbabwean" },
  { code: "OTHER", flag: "🌐", label: "Other" },
];
