/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RemoteCompanySetupRouteImport } from './routes/remote-company-setup'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebAdvertisingRouteImport } from './routes/services.web-advertising'
import { Route as ServicesResidencyRelocationRouteImport } from './routes/services.residency-relocation'
import { Route as ServicesOperationalSupportRouteImport } from './routes/services.operational-support'
import { Route as ServicesBusinessFormationRouteImport } from './routes/services.business-formation'
import { Route as ServicesBankingPreparationRouteImport } from './routes/services.banking-preparation'
import { Route as ServicesAmlComplianceRouteImport } from './routes/services.aml-compliance'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteCompanySetupRoute = RemoteCompanySetupRouteImport.update({
  id: '/remote-company-setup',
  path: '/remote-company-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebAdvertisingRoute = ServicesWebAdvertisingRouteImport.update({
  id: '/services/web-advertising',
  path: '/services/web-advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesResidencyRelocationRoute =
  ServicesResidencyRelocationRouteImport.update({
    id: '/services/residency-relocation',
    path: '/services/residency-relocation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesOperationalSupportRoute =
  ServicesOperationalSupportRouteImport.update({
    id: '/services/operational-support',
    path: '/services/operational-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBusinessFormationRoute =
  ServicesBusinessFormationRouteImport.update({
    id: '/services/business-formation',
    path: '/services/business-formation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBankingPreparationRoute =
  ServicesBankingPreparationRouteImport.update({
    id: '/services/banking-preparation',
    path: '/services/banking-preparation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAmlComplianceRoute = ServicesAmlComplianceRouteImport.update({
  id: '/services/aml-compliance',
  path: '/services/aml-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/remote-company-setup': typeof RemoteCompanySetupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/services/aml-compliance': typeof ServicesAmlComplianceRoute
  '/services/banking-preparation': typeof ServicesBankingPreparationRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/operational-support': typeof ServicesOperationalSupportRoute
  '/services/residency-relocation': typeof ServicesResidencyRelocationRoute
  '/services/web-advertising': typeof ServicesWebAdvertisingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/remote-company-setup': typeof RemoteCompanySetupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/services/aml-compliance': typeof ServicesAmlComplianceRoute
  '/services/banking-preparation': typeof ServicesBankingPreparationRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/operational-support': typeof ServicesOperationalSupportRoute
  '/services/residency-relocation': typeof ServicesResidencyRelocationRoute
  '/services/web-advertising': typeof ServicesWebAdvertisingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/advisor': typeof AdvisorRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/remote-company-setup': typeof RemoteCompanySetupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/services/aml-compliance': typeof ServicesAmlComplianceRoute
  '/services/banking-preparation': typeof ServicesBankingPreparationRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/operational-support': typeof ServicesOperationalSupportRoute
  '/services/residency-relocation': typeof ServicesResidencyRelocationRoute
  '/services/web-advertising': typeof ServicesWebAdvertisingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advisor'
    | '/login'
    | '/privacy-policy'
    | '/quote'
    | '/remote-company-setup'
    | '/terms'
    | '/admin'
    | '/portal'
    | '/services/aml-compliance'
    | '/services/banking-preparation'
    | '/services/business-formation'
    | '/services/operational-support'
    | '/services/residency-relocation'
    | '/services/web-advertising'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advisor'
    | '/login'
    | '/privacy-policy'
    | '/quote'
    | '/remote-company-setup'
    | '/terms'
    | '/admin'
    | '/portal'
    | '/services/aml-compliance'
    | '/services/banking-preparation'
    | '/services/business-formation'
    | '/services/operational-support'
    | '/services/residency-relocation'
    | '/services/web-advertising'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/advisor'
    | '/login'
    | '/privacy-policy'
    | '/quote'
    | '/remote-company-setup'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/services/aml-compliance'
    | '/services/banking-preparation'
    | '/services/business-formation'
    | '/services/operational-support'
    | '/services/residency-relocation'
    | '/services/web-advertising'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdvisorRoute: typeof AdvisorRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QuoteRoute: typeof QuoteRoute
  RemoteCompanySetupRoute: typeof RemoteCompanySetupRoute
  TermsRoute: typeof TermsRoute
  ServicesAmlComplianceRoute: typeof ServicesAmlComplianceRoute
  ServicesBankingPreparationRoute: typeof ServicesBankingPreparationRoute
  ServicesBusinessFormationRoute: typeof ServicesBusinessFormationRoute
  ServicesOperationalSupportRoute: typeof ServicesOperationalSupportRoute
  ServicesResidencyRelocationRoute: typeof ServicesResidencyRelocationRoute
  ServicesWebAdvertisingRoute: typeof ServicesWebAdvertisingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-company-setup': {
      id: '/remote-company-setup'
      path: '/remote-company-setup'
      fullPath: '/remote-company-setup'
      preLoaderRoute: typeof RemoteCompanySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-advertising': {
      id: '/services/web-advertising'
      path: '/services/web-advertising'
      fullPath: '/services/web-advertising'
      preLoaderRoute: typeof ServicesWebAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/residency-relocation': {
      id: '/services/residency-relocation'
      path: '/services/residency-relocation'
      fullPath: '/services/residency-relocation'
      preLoaderRoute: typeof ServicesResidencyRelocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/operational-support': {
      id: '/services/operational-support'
      path: '/services/operational-support'
      fullPath: '/services/operational-support'
      preLoaderRoute: typeof ServicesOperationalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-formation': {
      id: '/services/business-formation'
      path: '/services/business-formation'
      fullPath: '/services/business-formation'
      preLoaderRoute: typeof ServicesBusinessFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/banking-preparation': {
      id: '/services/banking-preparation'
      path: '/services/banking-preparation'
      fullPath: '/services/banking-preparation'
      preLoaderRoute: typeof ServicesBankingPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/aml-compliance': {
      id: '/services/aml-compliance'
      path: '/services/aml-compliance'
      fullPath: '/services/aml-compliance'
      preLoaderRoute: typeof ServicesAmlComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdvisorRoute: AdvisorRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QuoteRoute: QuoteRoute,
  RemoteCompanySetupRoute: RemoteCompanySetupRoute,
  TermsRoute: TermsRoute,
  ServicesAmlComplianceRoute: ServicesAmlComplianceRoute,
  ServicesBankingPreparationRoute: ServicesBankingPreparationRoute,
  ServicesBusinessFormationRoute: ServicesBusinessFormationRoute,
  ServicesOperationalSupportRoute: ServicesOperationalSupportRoute,
  ServicesResidencyRelocationRoute: ServicesResidencyRelocationRoute,
  ServicesWebAdvertisingRoute: ServicesWebAdvertisingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
