/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UaqCompanyFormationRouteImport } from './routes/uaq-company-formation'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StartRouteImport } from './routes/start'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SharjahCompanyFormationRouteImport } from './routes/sharjah-company-formation'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RemoteCompanySetupRouteImport } from './routes/remote-company-setup'
import { Route as RakCompanyFormationRouteImport } from './routes/rak-company-formation'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FujairahCompanyFormationRouteImport } from './routes/fujairah-company-formation'
import { Route as DubaiCompanyFormationRouteImport } from './routes/dubai-company-formation'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AjmanCompanyFormationRouteImport } from './routes/ajman-company-formation'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AbuDhabiCompanyFormationRouteImport } from './routes/abu-dhabi-company-formation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as ServicesWebAdvertisingRouteImport } from './routes/services.web-advertising'
import { Route as ServicesUaeCompanyFormationLocationsRouteImport } from './routes/services.uae-company-formation-locations'
import { Route as ServicesResidencyRelocationRouteImport } from './routes/services.residency-relocation'
import { Route as ServicesOperationalSupportRouteImport } from './routes/services.operational-support'
import { Route as ServicesBusinessFormationRouteImport } from './routes/services.business-formation'
import { Route as ServicesBankingPreparationRouteImport } from './routes/services.banking-preparation'
import { Route as ServicesAmlComplianceRouteImport } from './routes/services.aml-compliance'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiAdvisorChatRouteImport } from './routes/api/advisor.chat'

const UaqCompanyFormationRoute = UaqCompanyFormationRouteImport.update({
  id: '/uaq-company-formation',
  path: '/uaq-company-formation',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SharjahCompanyFormationRoute = SharjahCompanyFormationRouteImport.update({
  id: '/sharjah-company-formation',
  path: '/sharjah-company-formation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteCompanySetupRoute = RemoteCompanySetupRouteImport.update({
  id: '/remote-company-setup',
  path: '/remote-company-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RakCompanyFormationRoute = RakCompanyFormationRouteImport.update({
  id: '/rak-company-formation',
  path: '/rak-company-formation',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FujairahCompanyFormationRoute =
  FujairahCompanyFormationRouteImport.update({
    id: '/fujairah-company-formation',
    path: '/fujairah-company-formation',
    getParentRoute: () => rootRouteImport,
  } as any)
const DubaiCompanyFormationRoute = DubaiCompanyFormationRouteImport.update({
  id: '/dubai-company-formation',
  path: '/dubai-company-formation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AjmanCompanyFormationRoute = AjmanCompanyFormationRouteImport.update({
  id: '/ajman-company-formation',
  path: '/ajman-company-formation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AbuDhabiCompanyFormationRoute =
  AbuDhabiCompanyFormationRouteImport.update({
    id: '/abu-dhabi-company-formation',
    path: '/abu-dhabi-company-formation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const ServicesWebAdvertisingRoute = ServicesWebAdvertisingRouteImport.update({
  id: '/services/web-advertising',
  path: '/services/web-advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesUaeCompanyFormationLocationsRoute =
  ServicesUaeCompanyFormationLocationsRouteImport.update({
    id: '/services/uae-company-formation-locations',
    path: '/services/uae-company-formation-locations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesResidencyRelocationRoute =
  ServicesResidencyRelocationRouteImport.update({
    id: '/services/residency-relocation',
    path: '/services/residency-relocation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesOperationalSupportRoute =
  ServicesOperationalSupportRouteImport.update({
    id: '/services/operational-support',
    path: '/services/operational-support',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBusinessFormationRoute =
  ServicesBusinessFormationRouteImport.update({
    id: '/services/business-formation',
    path: '/services/business-formation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesBankingPreparationRoute =
  ServicesBankingPreparationRouteImport.update({
    id: '/services/banking-preparation',
    path: '/services/banking-preparation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesAmlComplianceRoute = ServicesAmlComplianceRouteImport.update({
  id: '/services/aml-compliance',
  path: '/services/aml-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InsightsRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAdvisorChatRoute = ApiAdvisorChatRouteImport.update({
  id: '/api/advisor/chat',
  path: '/api/advisor/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abu-dhabi-company-formation': typeof AbuDhabiCompanyFormationRoute
  '/advisor': typeof AdvisorRoute
  '/ajman-company-formation': typeof AjmanCompanyFormationRoute
  '/blog': typeof BlogRoute
  '/dubai-company-formation': typeof DubaiCompanyFormationRoute
  '/fujairah-company-formation': typeof FujairahCompanyFormationRoute
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/rak-company-formation': typeof RakCompanyFormationRoute
  '/remote-company-setup': typeof RemoteCompanySetupRoute
  '/resources': typeof ResourcesRoute
  '/sharjah-company-formation': typeof SharjahCompanyFormationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/uaq-company-formation': typeof UaqCompanyFormationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/aml-compliance': typeof ServicesAmlComplianceRoute
  '/services/banking-preparation': typeof ServicesBankingPreparationRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/operational-support': typeof ServicesOperationalSupportRoute
  '/services/residency-relocation': typeof ServicesResidencyRelocationRoute
  '/services/uae-company-formation-locations': typeof ServicesUaeCompanyFormationLocationsRoute
  '/services/web-advertising': typeof ServicesWebAdvertisingRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/advisor/chat': typeof ApiAdvisorChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abu-dhabi-company-formation': typeof AbuDhabiCompanyFormationRoute
  '/advisor': typeof AdvisorRoute
  '/ajman-company-formation': typeof AjmanCompanyFormationRoute
  '/blog': typeof BlogRoute
  '/dubai-company-formation': typeof DubaiCompanyFormationRoute
  '/fujairah-company-formation': typeof FujairahCompanyFormationRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/rak-company-formation': typeof RakCompanyFormationRoute
  '/remote-company-setup': typeof RemoteCompanySetupRoute
  '/resources': typeof ResourcesRoute
  '/sharjah-company-formation': typeof SharjahCompanyFormationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/uaq-company-formation': typeof UaqCompanyFormationRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/aml-compliance': typeof ServicesAmlComplianceRoute
  '/services/banking-preparation': typeof ServicesBankingPreparationRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/operational-support': typeof ServicesOperationalSupportRoute
  '/services/residency-relocation': typeof ServicesResidencyRelocationRoute
  '/services/uae-company-formation-locations': typeof ServicesUaeCompanyFormationLocationsRoute
  '/services/web-advertising': typeof ServicesWebAdvertisingRoute
  '/insights': typeof InsightsIndexRoute
  '/api/advisor/chat': typeof ApiAdvisorChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/abu-dhabi-company-formation': typeof AbuDhabiCompanyFormationRoute
  '/advisor': typeof AdvisorRoute
  '/ajman-company-formation': typeof AjmanCompanyFormationRoute
  '/blog': typeof BlogRoute
  '/dubai-company-formation': typeof DubaiCompanyFormationRoute
  '/fujairah-company-formation': typeof FujairahCompanyFormationRoute
  '/insights': typeof InsightsRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/quote': typeof QuoteRoute
  '/rak-company-formation': typeof RakCompanyFormationRoute
  '/remote-company-setup': typeof RemoteCompanySetupRoute
  '/resources': typeof ResourcesRoute
  '/sharjah-company-formation': typeof SharjahCompanyFormationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/uaq-company-formation': typeof UaqCompanyFormationRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/aml-compliance': typeof ServicesAmlComplianceRoute
  '/services/banking-preparation': typeof ServicesBankingPreparationRoute
  '/services/business-formation': typeof ServicesBusinessFormationRoute
  '/services/operational-support': typeof ServicesOperationalSupportRoute
  '/services/residency-relocation': typeof ServicesResidencyRelocationRoute
  '/services/uae-company-formation-locations': typeof ServicesUaeCompanyFormationLocationsRoute
  '/services/web-advertising': typeof ServicesWebAdvertisingRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/advisor/chat': typeof ApiAdvisorChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/abu-dhabi-company-formation'
    | '/advisor'
    | '/ajman-company-formation'
    | '/blog'
    | '/dubai-company-formation'
    | '/fujairah-company-formation'
    | '/insights'
    | '/login'
    | '/privacy-policy'
    | '/quote'
    | '/rak-company-formation'
    | '/remote-company-setup'
    | '/resources'
    | '/sharjah-company-formation'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/uaq-company-formation'
    | '/admin'
    | '/portal'
    | '/insights/$slug'
    | '/services/aml-compliance'
    | '/services/banking-preparation'
    | '/services/business-formation'
    | '/services/operational-support'
    | '/services/residency-relocation'
    | '/services/uae-company-formation-locations'
    | '/services/web-advertising'
    | '/insights/'
    | '/api/advisor/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/abu-dhabi-company-formation'
    | '/advisor'
    | '/ajman-company-formation'
    | '/blog'
    | '/dubai-company-formation'
    | '/fujairah-company-formation'
    | '/login'
    | '/privacy-policy'
    | '/quote'
    | '/rak-company-formation'
    | '/remote-company-setup'
    | '/resources'
    | '/sharjah-company-formation'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/uaq-company-formation'
    | '/admin'
    | '/portal'
    | '/insights/$slug'
    | '/services/aml-compliance'
    | '/services/banking-preparation'
    | '/services/business-formation'
    | '/services/operational-support'
    | '/services/residency-relocation'
    | '/services/uae-company-formation-locations'
    | '/services/web-advertising'
    | '/insights'
    | '/api/advisor/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/abu-dhabi-company-formation'
    | '/advisor'
    | '/ajman-company-formation'
    | '/blog'
    | '/dubai-company-formation'
    | '/fujairah-company-formation'
    | '/insights'
    | '/login'
    | '/privacy-policy'
    | '/quote'
    | '/rak-company-formation'
    | '/remote-company-setup'
    | '/resources'
    | '/sharjah-company-formation'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/uaq-company-formation'
    | '/_authenticated/admin'
    | '/_authenticated/portal'
    | '/insights/$slug'
    | '/services/aml-compliance'
    | '/services/banking-preparation'
    | '/services/business-formation'
    | '/services/operational-support'
    | '/services/residency-relocation'
    | '/services/uae-company-formation-locations'
    | '/services/web-advertising'
    | '/insights/'
    | '/api/advisor/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AbuDhabiCompanyFormationRoute: typeof AbuDhabiCompanyFormationRoute
  AdvisorRoute: typeof AdvisorRoute
  AjmanCompanyFormationRoute: typeof AjmanCompanyFormationRoute
  BlogRoute: typeof BlogRoute
  DubaiCompanyFormationRoute: typeof DubaiCompanyFormationRoute
  FujairahCompanyFormationRoute: typeof FujairahCompanyFormationRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  QuoteRoute: typeof QuoteRoute
  RakCompanyFormationRoute: typeof RakCompanyFormationRoute
  RemoteCompanySetupRoute: typeof RemoteCompanySetupRoute
  ResourcesRoute: typeof ResourcesRoute
  SharjahCompanyFormationRoute: typeof SharjahCompanyFormationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  UaqCompanyFormationRoute: typeof UaqCompanyFormationRoute
  ServicesAmlComplianceRoute: typeof ServicesAmlComplianceRoute
  ServicesBankingPreparationRoute: typeof ServicesBankingPreparationRoute
  ServicesBusinessFormationRoute: typeof ServicesBusinessFormationRoute
  ServicesOperationalSupportRoute: typeof ServicesOperationalSupportRoute
  ServicesResidencyRelocationRoute: typeof ServicesResidencyRelocationRoute
  ServicesUaeCompanyFormationLocationsRoute: typeof ServicesUaeCompanyFormationLocationsRoute
  ServicesWebAdvertisingRoute: typeof ServicesWebAdvertisingRoute
  ApiAdvisorChatRoute: typeof ApiAdvisorChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uaq-company-formation': {
      id: '/uaq-company-formation'
      path: '/uaq-company-formation'
      fullPath: '/uaq-company-formation'
      preLoaderRoute: typeof UaqCompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharjah-company-formation': {
      id: '/sharjah-company-formation'
      path: '/sharjah-company-formation'
      fullPath: '/sharjah-company-formation'
      preLoaderRoute: typeof SharjahCompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-company-setup': {
      id: '/remote-company-setup'
      path: '/remote-company-setup'
      fullPath: '/remote-company-setup'
      preLoaderRoute: typeof RemoteCompanySetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rak-company-formation': {
      id: '/rak-company-formation'
      path: '/rak-company-formation'
      fullPath: '/rak-company-formation'
      preLoaderRoute: typeof RakCompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fujairah-company-formation': {
      id: '/fujairah-company-formation'
      path: '/fujairah-company-formation'
      fullPath: '/fujairah-company-formation'
      preLoaderRoute: typeof FujairahCompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dubai-company-formation': {
      id: '/dubai-company-formation'
      path: '/dubai-company-formation'
      fullPath: '/dubai-company-formation'
      preLoaderRoute: typeof DubaiCompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajman-company-formation': {
      id: '/ajman-company-formation'
      path: '/ajman-company-formation'
      fullPath: '/ajman-company-formation'
      preLoaderRoute: typeof AjmanCompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abu-dhabi-company-formation': {
      id: '/abu-dhabi-company-formation'
      path: '/abu-dhabi-company-formation'
      fullPath: '/abu-dhabi-company-formation'
      preLoaderRoute: typeof AbuDhabiCompanyFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/services/web-advertising': {
      id: '/services/web-advertising'
      path: '/services/web-advertising'
      fullPath: '/services/web-advertising'
      preLoaderRoute: typeof ServicesWebAdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/uae-company-formation-locations': {
      id: '/services/uae-company-formation-locations'
      path: '/services/uae-company-formation-locations'
      fullPath: '/services/uae-company-formation-locations'
      preLoaderRoute: typeof ServicesUaeCompanyFormationLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/residency-relocation': {
      id: '/services/residency-relocation'
      path: '/services/residency-relocation'
      fullPath: '/services/residency-relocation'
      preLoaderRoute: typeof ServicesResidencyRelocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/operational-support': {
      id: '/services/operational-support'
      path: '/services/operational-support'
      fullPath: '/services/operational-support'
      preLoaderRoute: typeof ServicesOperationalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-formation': {
      id: '/services/business-formation'
      path: '/services/business-formation'
      fullPath: '/services/business-formation'
      preLoaderRoute: typeof ServicesBusinessFormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/banking-preparation': {
      id: '/services/banking-preparation'
      path: '/services/banking-preparation'
      fullPath: '/services/banking-preparation'
      preLoaderRoute: typeof ServicesBankingPreparationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/aml-compliance': {
      id: '/services/aml-compliance'
      path: '/services/aml-compliance'
      fullPath: '/services/aml-compliance'
      preLoaderRoute: typeof ServicesAmlComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/advisor/chat': {
      id: '/api/advisor/chat'
      path: '/api/advisor/chat'
      fullPath: '/api/advisor/chat'
      preLoaderRoute: typeof ApiAdvisorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface InsightsRouteChildren {
  InsightsSlugRoute: typeof InsightsSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsSlugRoute: InsightsSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AbuDhabiCompanyFormationRoute: AbuDhabiCompanyFormationRoute,
  AdvisorRoute: AdvisorRoute,
  AjmanCompanyFormationRoute: AjmanCompanyFormationRoute,
  BlogRoute: BlogRoute,
  DubaiCompanyFormationRoute: DubaiCompanyFormationRoute,
  FujairahCompanyFormationRoute: FujairahCompanyFormationRoute,
  InsightsRoute: InsightsRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  QuoteRoute: QuoteRoute,
  RakCompanyFormationRoute: RakCompanyFormationRoute,
  RemoteCompanySetupRoute: RemoteCompanySetupRoute,
  ResourcesRoute: ResourcesRoute,
  SharjahCompanyFormationRoute: SharjahCompanyFormationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  UaqCompanyFormationRoute: UaqCompanyFormationRoute,
  ServicesAmlComplianceRoute: ServicesAmlComplianceRoute,
  ServicesBankingPreparationRoute: ServicesBankingPreparationRoute,
  ServicesBusinessFormationRoute: ServicesBusinessFormationRoute,
  ServicesOperationalSupportRoute: ServicesOperationalSupportRoute,
  ServicesResidencyRelocationRoute: ServicesResidencyRelocationRoute,
  ServicesUaeCompanyFormationLocationsRoute:
    ServicesUaeCompanyFormationLocationsRoute,
  ServicesWebAdvertisingRoute: ServicesWebAdvertisingRoute,
  ApiAdvisorChatRoute: ApiAdvisorChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
