// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.

import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getServerEnv(key: string): string | undefined {
  return (
    process.env?.[key] ||
    (globalThis as any).__env__?.[key] ||
    (globalThis as any).env?.[key] ||
    (globalThis as any).__cf_env__?.[key]
  );
}

function createSupabaseAdminClient(): SupabaseClient<Database> {
  const SUPABASE_URL = getServerEnv('SUPABASE_URL');
  const SUPABASE_SERVICE_ROLE_KEY = getServerEnv('SUPABASE_SERVICE_ROLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

// No module-level singleton — a fresh client is created per access
// so that Cloudflare env hydration (which happens at request time) is always picked up.
//
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as SupabaseClient<Database>, {
  get(_, prop, receiver) {
    // Create a fresh client on every property access so we always read
    // the latest process.env values, regardless of when this module was loaded.
    const client = createSupabaseAdminClient();
    return Reflect.get(client, prop, receiver);
  },
});
