// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.

import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getServerEnv(key: string): string | undefined {
 const fromGlobalEnv = (globalThis as any).__env__?.[key];
 const fromGlobalEnv2 = (globalThis as any).env?.[key];
 const fromCfEnv = (globalThis as any).__cf_env__?.[key];
 const fromProcess = process.env?.[key];

 console.log(`[ENV DEBUG] ${key}:`, {
   globalThis__env__: fromGlobalEnv ? "SET" : "undefined",
   globalThis_env: fromGlobalEnv2 ? "SET" : "undefined",
   __cf_env__: fromCfEnv ? "SET" : "undefined",
   process_env: fromProcess ? "SET" : "undefined",
 });

 return fromGlobalEnv || fromGlobalEnv2 || fromCfEnv || fromProcess;
}

function createSupabaseAdminClient(): SupabaseClient<Database> {
 const SUPABASE_URL = getServerEnv('SUPABASE_URL');
 const SUPABASE_SERVICE_ROLE_KEY = getServerEnv('SUPABASE_SERVICE_ROLE_KEY');

 if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
   const missing = [
     ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
     ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
   ];
   const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
   console.error(`[Supabase] ${message}`);
   throw new Error(message);
 }

 return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
   auth: {
     storage: undefined,
     persistSession: false,
     autoRefreshToken: false,
   },
 });
}

// No module-level singleton — a fresh client is created per access
// so that Cloudflare env hydration (which happens at request time) is always picked up.
//
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as SupabaseClient<Database>, {
 get(_, prop, receiver) {
   const client = createSupabaseAdminClient();
   return Reflect.get(client, prop, receiver);
 },
});
